### ISSUE TITLE
Wrong indent in application.yml for postgres-reactive

### ISSUE THREAD

**Issue by bufferings** [micronaut-projects/micronaut-profiles#148]
https://github.com/micronaut-projects/micronaut-profiles/blob/v1.1.0/base/features/postgres-reactive/skeleton/src/main/resources/application.yml

The indent is wrong:

```yaml
postgres:
  reactive:
    client:
    port: 5432
    host: localhost
    database: @app.name@
    # user: user
    # password: password
    # maxSize: 5
```

This works:

```yaml
postgres:
  reactive:
    client:
        port: 5432
        host: localhost
        database: @app.name@
        # user: user
        # password: password
        # maxSize: 5
```
