### ISSUE TITLE
Update Spek dependencies to Spek2

### ISSUE THREAD

**Issue by orevial** [micronaut-projects/micronaut-profiles#194]
Currently when we create an application with spek feature using mn command, following spek dependencies are added:

```yaml
  - scope: testCompile
    coords: org.jetbrains.spek:spek-api:1.1.5
  - scope: testRuntime
    coords: org.jetbrains.spek:spek-junit-platform-engine:1.1.5
```

It would however be good to update those dependencies to use Spek2 as various Micronaut guides already do.
New dependencies:

```yaml
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:$spek_version"
    testRuntimeOnly "org.spekframework.spek2:spek-runner-junit5:$spek_version"
```
